version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo Nothing to do in pre-build phase
  build:
    commands:
      - echo Build started
      - mvn install -DskipTests=true
  post_build:
    commands:
      - echo Nothing to do in the post_build phase
artifacts:
  files:
    - target/customer-service.jar