version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging to ECR
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 211125731692.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=211125731692.dkr.ecr.ap-south-1.amazonaws.com/aditya_repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build docker image
      - docker build -t $REPOSITORY_URI:$SERVICE_NAME:latest .
  post_build:
    commands:
      - echo docker image build completed
      - echo pushing docker image
      - echo $REPOSITORY_URI
      - docker push $REPOSITORY_URI:$SERVICE_NAME:latest
artifacts:
  files:
    - target/customer-service.jar
